CREATE DATABASE vet_clinic;

CREATE TABLE animals (
    id int,
    name text,
    date_of_birth date,
    escape_attempts int,
    neutered boolean,
    weight_kg decimal,
    PRIMARY KEY(id)
);

ALTER TABLE animals
ADD COLUMN species  VARCHAR(150);


CREATE TABLE owners (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
  (START WITH 1 INCREMENT BY 1),
  full_name VARCHAR(100),
  age INT
);


CREATE TABLE species (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
  (START WITH 1 INCREMENT BY 1),
  name VARCHAR(100)
);


ALTER TABLE animals
DROP COLUMN species,
ADD COLUMN species_id INT REFERENCES species(id),
ADD COLUMN owner_id INT REFERENCES owners(id);